// Generated by CoffeeScript 1.7.0
(function() {
  var CreativeInventoryPlugin, InventoryDialog,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InventoryDialog = (require('voxel-inventory-dialog')).InventoryDialog;

  module.exports = function(game, opts) {
    return new CreativeInventoryPlugin(game, opts);
  };

  CreativeInventoryPlugin = (function(_super) {
    __extends(CreativeInventoryPlugin, _super);

    function CreativeInventoryPlugin(game, opts) {
      var div;
      this.game = game;
      div = document.createElement('div');
      div.textContent = 'hello world';
      CreativeInventoryPlugin.__super__.constructor.call(this, game, {
        upper: [div]
      });
    }

    CreativeInventoryPlugin.prototype.enable = function() {};

    CreativeInventoryPlugin.prototype.disable = function() {};

    return CreativeInventoryPlugin;

  })(InventoryDialog);

}).call(this);
